// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: part_manifest.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.rajmani7584.payloaddumper.engine.part_manifest;

@kotlin.jvm.JvmName("-initializedstExtent")
public inline fun dstExtent(block: com.rajmani7584.payloaddumper.engine.part_manifest.DstExtentKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent =
  com.rajmani7584.payloaddumper.engine.part_manifest.DstExtentKt.Dsl._create(com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `part_manifest.DstExtent`
 */
public object DstExtentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent = _builder.build()

    /**
     * `optional uint64 num_blocks = 1;`
     */
    public var numBlocks: kotlin.Long
      @kotlin.jvm.JvmName("getNumBlocks")
        get() = _builder.numBlocks
      @kotlin.jvm.JvmName("setNumBlocks")
        set(value) {
        _builder.numBlocks = value
      }
    /**
     * `optional uint64 num_blocks = 1;`
     */
    public fun clearNumBlocks() {
      _builder.clearNumBlocks()
    }
    /**
     * `optional uint64 num_blocks = 1;`
     * @return Whether the numBlocks field is set.
     */
    public fun hasNumBlocks(): kotlin.Boolean {
      return _builder.hasNumBlocks()
    }
  }
}
public inline fun com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent.copy(block: `com.rajmani7584.payloaddumper.engine.part_manifest`.DstExtentKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent =
  `com.rajmani7584.payloaddumper.engine.part_manifest`.DstExtentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

