// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: part_manifest.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.rajmani7584.payloaddumper.engine.part_manifest;

@kotlin.jvm.JvmName("-initializeoperation")
public inline fun operation(block: com.rajmani7584.payloaddumper.engine.part_manifest.OperationKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation =
  com.rajmani7584.payloaddumper.engine.part_manifest.OperationKt.Dsl._create(com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `part_manifest.Operation`
 */
public object OperationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation = _builder.build()

    /**
     * `optional uint64 data_offset = 1;`
     */
    public var dataOffset: kotlin.Long
      @kotlin.jvm.JvmName("getDataOffset")
        get() = _builder.dataOffset
      @kotlin.jvm.JvmName("setDataOffset")
        set(value) {
        _builder.dataOffset = value
      }
    /**
     * `optional uint64 data_offset = 1;`
     */
    public fun clearDataOffset() {
      _builder.clearDataOffset()
    }
    /**
     * `optional uint64 data_offset = 1;`
     * @return Whether the dataOffset field is set.
     */
    public fun hasDataOffset(): kotlin.Boolean {
      return _builder.hasDataOffset()
    }

    /**
     * `optional uint64 data_length = 2;`
     */
    public var dataLength: kotlin.Long
      @kotlin.jvm.JvmName("getDataLength")
        get() = _builder.dataLength
      @kotlin.jvm.JvmName("setDataLength")
        set(value) {
        _builder.dataLength = value
      }
    /**
     * `optional uint64 data_length = 2;`
     */
    public fun clearDataLength() {
      _builder.clearDataLength()
    }
    /**
     * `optional uint64 data_length = 2;`
     * @return Whether the dataLength field is set.
     */
    public fun hasDataLength(): kotlin.Boolean {
      return _builder.hasDataLength()
    }

    /**
     * `required string sha_hash = 3;`
     */
    public var shaHash: kotlin.String
      @kotlin.jvm.JvmName("getShaHash")
        get() = _builder.shaHash
      @kotlin.jvm.JvmName("setShaHash")
        set(value) {
        _builder.shaHash = value
      }
    /**
     * `required string sha_hash = 3;`
     */
    public fun clearShaHash() {
      _builder.clearShaHash()
    }
    /**
     * `required string sha_hash = 3;`
     * @return Whether the shaHash field is set.
     */
    public fun hasShaHash(): kotlin.Boolean {
      return _builder.hasShaHash()
    }

    /**
     * `required .part_manifest.Operation.Type type = 4;`
     */
    public var type: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation.Type
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    /**
     * `required .part_manifest.Operation.Type type = 4;`
     */
    public fun clearType() {
      _builder.clearType()
    }
    /**
     * `required .part_manifest.Operation.Type type = 4;`
     * @return Whether the type field is set.
     */
    public fun hasType(): kotlin.Boolean {
      return _builder.hasType()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DstExtentsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .part_manifest.DstExtent dst_extents = 5;`
     */
     public val dstExtents: com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent, DstExtentsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.dstExtentsList
      )
    /**
     * `repeated .part_manifest.DstExtent dst_extents = 5;`
     * @param value The dstExtents to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addDstExtents")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent, DstExtentsProxy>.add(value: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent) {
      _builder.addDstExtents(value)
    }
    /**
     * `repeated .part_manifest.DstExtent dst_extents = 5;`
     * @param value The dstExtents to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignDstExtents")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent, DstExtentsProxy>.plusAssign(value: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent) {
      add(value)
    }
    /**
     * `repeated .part_manifest.DstExtent dst_extents = 5;`
     * @param values The dstExtents to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllDstExtents")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent, DstExtentsProxy>.addAll(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent>) {
      _builder.addAllDstExtents(values)
    }
    /**
     * `repeated .part_manifest.DstExtent dst_extents = 5;`
     * @param values The dstExtents to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllDstExtents")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent, DstExtentsProxy>.plusAssign(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent>) {
      addAll(values)
    }
    /**
     * `repeated .part_manifest.DstExtent dst_extents = 5;`
     * @param index The index to set the value at.
     * @param value The dstExtents to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setDstExtents")
    public operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent, DstExtentsProxy>.set(index: kotlin.Int, value: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent) {
      _builder.setDstExtents(index, value)
    }
    /**
     * `repeated .part_manifest.DstExtent dst_extents = 5;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearDstExtents")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.DstExtent, DstExtentsProxy>.clear() {
      _builder.clearDstExtents()
    }
  }
}
public inline fun com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation.copy(block: `com.rajmani7584.payloaddumper.engine.part_manifest`.OperationKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation =
  `com.rajmani7584.payloaddumper.engine.part_manifest`.OperationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

