// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: part_manifest.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.rajmani7584.payloaddumper.engine.part_manifest;

@kotlin.jvm.JvmName("-initializepartInfo")
public inline fun partInfo(block: com.rajmani7584.payloaddumper.engine.part_manifest.PartInfoKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartInfo =
  com.rajmani7584.payloaddumper.engine.part_manifest.PartInfoKt.Dsl._create(com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `part_manifest.PartInfo`
 */
public object PartInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartInfo = _builder.build()

    /**
     * `optional uint64 size = 1;`
     */
    public var size: kotlin.Long
      @kotlin.jvm.JvmName("getSize")
        get() = _builder.size
      @kotlin.jvm.JvmName("setSize")
        set(value) {
        _builder.size = value
      }
    /**
     * `optional uint64 size = 1;`
     */
    public fun clearSize() {
      _builder.clearSize()
    }
    /**
     * `optional uint64 size = 1;`
     * @return Whether the size field is set.
     */
    public fun hasSize(): kotlin.Boolean {
      return _builder.hasSize()
    }

    /**
     * `optional bytes hash = 2;`
     */
    public var hash: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getHash")
        get() = _builder.hash
      @kotlin.jvm.JvmName("setHash")
        set(value) {
        _builder.hash = value
      }
    /**
     * `optional bytes hash = 2;`
     */
    public fun clearHash() {
      _builder.clearHash()
    }
    /**
     * `optional bytes hash = 2;`
     * @return Whether the hash field is set.
     */
    public fun hasHash(): kotlin.Boolean {
      return _builder.hasHash()
    }
  }
}
public inline fun com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartInfo.copy(block: `com.rajmani7584.payloaddumper.engine.part_manifest`.PartInfoKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartInfo =
  `com.rajmani7584.payloaddumper.engine.part_manifest`.PartInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

