// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: part_manifest.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.rajmani7584.payloaddumper.engine.part_manifest;

@kotlin.jvm.JvmName("-initializepartManifest")
public inline fun partManifest(block: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartManifest =
  com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestKt.Dsl._create(com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartManifest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `part_manifest.PartManifest`
 */
public object PartManifestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartManifest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartManifest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartManifest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PartitionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .part_manifest.UpdateInfo partitions = 2;`
     */
     public val partitions: com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo, PartitionsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.partitionsList
      )
    /**
     * `repeated .part_manifest.UpdateInfo partitions = 2;`
     * @param value The partitions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addPartitions")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo, PartitionsProxy>.add(value: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo) {
      _builder.addPartitions(value)
    }
    /**
     * `repeated .part_manifest.UpdateInfo partitions = 2;`
     * @param value The partitions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignPartitions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo, PartitionsProxy>.plusAssign(value: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo) {
      add(value)
    }
    /**
     * `repeated .part_manifest.UpdateInfo partitions = 2;`
     * @param values The partitions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllPartitions")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo, PartitionsProxy>.addAll(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo>) {
      _builder.addAllPartitions(values)
    }
    /**
     * `repeated .part_manifest.UpdateInfo partitions = 2;`
     * @param values The partitions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllPartitions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo, PartitionsProxy>.plusAssign(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo>) {
      addAll(values)
    }
    /**
     * `repeated .part_manifest.UpdateInfo partitions = 2;`
     * @param index The index to set the value at.
     * @param value The partitions to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setPartitions")
    public operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo, PartitionsProxy>.set(index: kotlin.Int, value: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo) {
      _builder.setPartitions(index, value)
    }
    /**
     * `repeated .part_manifest.UpdateInfo partitions = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearPartitions")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo, PartitionsProxy>.clear() {
      _builder.clearPartitions()
    }

    /**
     * `optional uint32 block_size = 3;`
     */
    public var blockSize: kotlin.Int
      @kotlin.jvm.JvmName("getBlockSize")
        get() = _builder.blockSize
      @kotlin.jvm.JvmName("setBlockSize")
        set(value) {
        _builder.blockSize = value
      }
    /**
     * `optional uint32 block_size = 3;`
     */
    public fun clearBlockSize() {
      _builder.clearBlockSize()
    }
    /**
     * `optional uint32 block_size = 3;`
     * @return Whether the blockSize field is set.
     */
    public fun hasBlockSize(): kotlin.Boolean {
      return _builder.hasBlockSize()
    }
  }
}
public inline fun com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartManifest.copy(block: `com.rajmani7584.payloaddumper.engine.part_manifest`.PartManifestKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartManifest =
  `com.rajmani7584.payloaddumper.engine.part_manifest`.PartManifestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

