// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: part_manifest.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.rajmani7584.payloaddumper.engine.part_manifest;

@kotlin.jvm.JvmName("-initializeupdateInfo")
public inline fun updateInfo(block: com.rajmani7584.payloaddumper.engine.part_manifest.UpdateInfoKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo =
  com.rajmani7584.payloaddumper.engine.part_manifest.UpdateInfoKt.Dsl._create(com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `part_manifest.UpdateInfo`
 */
public object UpdateInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo = _builder.build()

    /**
     * `required string partition_name = 1;`
     */
    public var partitionName: kotlin.String
      @kotlin.jvm.JvmName("getPartitionName")
        get() = _builder.partitionName
      @kotlin.jvm.JvmName("setPartitionName")
        set(value) {
        _builder.partitionName = value
      }
    /**
     * `required string partition_name = 1;`
     */
    public fun clearPartitionName() {
      _builder.clearPartitionName()
    }
    /**
     * `required string partition_name = 1;`
     * @return Whether the partitionName field is set.
     */
    public fun hasPartitionName(): kotlin.Boolean {
      return _builder.hasPartitionName()
    }

    /**
     * `optional .part_manifest.PartInfo new_partition_info = 2;`
     */
    public var newPartitionInfo: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartInfo
      @kotlin.jvm.JvmName("getNewPartitionInfo")
        get() = _builder.newPartitionInfo
      @kotlin.jvm.JvmName("setNewPartitionInfo")
        set(value) {
        _builder.newPartitionInfo = value
      }
    /**
     * `optional .part_manifest.PartInfo new_partition_info = 2;`
     */
    public fun clearNewPartitionInfo() {
      _builder.clearNewPartitionInfo()
    }
    /**
     * `optional .part_manifest.PartInfo new_partition_info = 2;`
     * @return Whether the newPartitionInfo field is set.
     */
    public fun hasNewPartitionInfo(): kotlin.Boolean {
      return _builder.hasNewPartitionInfo()
    }

    public val UpdateInfoKt.Dsl.newPartitionInfoOrNull: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartInfo?
      get() = _builder.newPartitionInfoOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OperationsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .part_manifest.Operation operations = 3;`
     */
     public val operations: com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation, OperationsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.operationsList
      )
    /**
     * `repeated .part_manifest.Operation operations = 3;`
     * @param value The operations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addOperations")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation, OperationsProxy>.add(value: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation) {
      _builder.addOperations(value)
    }
    /**
     * `repeated .part_manifest.Operation operations = 3;`
     * @param value The operations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignOperations")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation, OperationsProxy>.plusAssign(value: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation) {
      add(value)
    }
    /**
     * `repeated .part_manifest.Operation operations = 3;`
     * @param values The operations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllOperations")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation, OperationsProxy>.addAll(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation>) {
      _builder.addAllOperations(values)
    }
    /**
     * `repeated .part_manifest.Operation operations = 3;`
     * @param values The operations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllOperations")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation, OperationsProxy>.plusAssign(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation>) {
      addAll(values)
    }
    /**
     * `repeated .part_manifest.Operation operations = 3;`
     * @param index The index to set the value at.
     * @param value The operations to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setOperations")
    public operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation, OperationsProxy>.set(index: kotlin.Int, value: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation) {
      _builder.setOperations(index, value)
    }
    /**
     * `repeated .part_manifest.Operation operations = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearOperations")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.Operation, OperationsProxy>.clear() {
      _builder.clearOperations()
    }

    /**
     * `required bool incremental = 4;`
     */
    public var incremental: kotlin.Boolean
      @kotlin.jvm.JvmName("getIncremental")
        get() = _builder.incremental
      @kotlin.jvm.JvmName("setIncremental")
        set(value) {
        _builder.incremental = value
      }
    /**
     * `required bool incremental = 4;`
     */
    public fun clearIncremental() {
      _builder.clearIncremental()
    }
    /**
     * `required bool incremental = 4;`
     * @return Whether the incremental field is set.
     */
    public fun hasIncremental(): kotlin.Boolean {
      return _builder.hasIncremental()
    }
  }
}
public inline fun com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo.copy(block: `com.rajmani7584.payloaddumper.engine.part_manifest`.UpdateInfoKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfo =
  `com.rajmani7584.payloaddumper.engine.part_manifest`.UpdateInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.UpdateInfoOrBuilder.newPartitionInfoOrNull: com.rajmani7584.payloaddumper.engine.part_manifest.PartManifestOuterClass.PartInfo?
  get() = if (hasNewPartitionInfo()) getNewPartitionInfo() else null

