// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: update_metadata.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.rajmani7584.payloaddumper.engine.chromeos_update_engine;

@kotlin.jvm.JvmName("-initializedynamicPartitionMetadata")
public inline fun dynamicPartitionMetadata(block: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.DynamicPartitionMetadataKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionMetadata =
  com.rajmani7584.payloaddumper.engine.chromeos_update_engine.DynamicPartitionMetadataKt.Dsl._create(com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionMetadata.newBuilder()).apply { block() }._build()
/**
 * ```
 * Metadata related to all dynamic partitions.
 * ```
 *
 * Protobuf type `chromeos_update_engine.DynamicPartitionMetadata`
 */
public object DynamicPartitionMetadataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionMetadata.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionMetadata.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionMetadata = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class GroupsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * All updatable groups present in |partitions| of this DeltaArchiveManifest.
     * - If an updatable group is on the device but not in the manifest, it is
     * not updated. Hence, the group will not be resized, and partitions cannot
     * be added to or removed from the group.
     * - If an updatable group is in the manifest but not on the device, the group
     * is added to the device.
     * ```
     *
     * `repeated .chromeos_update_engine.DynamicPartitionGroup groups = 1;`
     */
     public val groups: com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup, GroupsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.groupsList
      )
    /**
     * ```
     * All updatable groups present in |partitions| of this DeltaArchiveManifest.
     * - If an updatable group is on the device but not in the manifest, it is
     * not updated. Hence, the group will not be resized, and partitions cannot
     * be added to or removed from the group.
     * - If an updatable group is in the manifest but not on the device, the group
     * is added to the device.
     * ```
     *
     * `repeated .chromeos_update_engine.DynamicPartitionGroup groups = 1;`
     * @param value The groups to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addGroups")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup, GroupsProxy>.add(value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup) {
      _builder.addGroups(value)
    }
    /**
     * ```
     * All updatable groups present in |partitions| of this DeltaArchiveManifest.
     * - If an updatable group is on the device but not in the manifest, it is
     * not updated. Hence, the group will not be resized, and partitions cannot
     * be added to or removed from the group.
     * - If an updatable group is in the manifest but not on the device, the group
     * is added to the device.
     * ```
     *
     * `repeated .chromeos_update_engine.DynamicPartitionGroup groups = 1;`
     * @param value The groups to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignGroups")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup, GroupsProxy>.plusAssign(value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup) {
      add(value)
    }
    /**
     * ```
     * All updatable groups present in |partitions| of this DeltaArchiveManifest.
     * - If an updatable group is on the device but not in the manifest, it is
     * not updated. Hence, the group will not be resized, and partitions cannot
     * be added to or removed from the group.
     * - If an updatable group is in the manifest but not on the device, the group
     * is added to the device.
     * ```
     *
     * `repeated .chromeos_update_engine.DynamicPartitionGroup groups = 1;`
     * @param values The groups to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllGroups")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup, GroupsProxy>.addAll(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup>) {
      _builder.addAllGroups(values)
    }
    /**
     * ```
     * All updatable groups present in |partitions| of this DeltaArchiveManifest.
     * - If an updatable group is on the device but not in the manifest, it is
     * not updated. Hence, the group will not be resized, and partitions cannot
     * be added to or removed from the group.
     * - If an updatable group is in the manifest but not on the device, the group
     * is added to the device.
     * ```
     *
     * `repeated .chromeos_update_engine.DynamicPartitionGroup groups = 1;`
     * @param values The groups to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllGroups")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup, GroupsProxy>.plusAssign(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup>) {
      addAll(values)
    }
    /**
     * ```
     * All updatable groups present in |partitions| of this DeltaArchiveManifest.
     * - If an updatable group is on the device but not in the manifest, it is
     * not updated. Hence, the group will not be resized, and partitions cannot
     * be added to or removed from the group.
     * - If an updatable group is in the manifest but not on the device, the group
     * is added to the device.
     * ```
     *
     * `repeated .chromeos_update_engine.DynamicPartitionGroup groups = 1;`
     * @param index The index to set the value at.
     * @param value The groups to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setGroups")
    public operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup, GroupsProxy>.set(index: kotlin.Int, value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup) {
      _builder.setGroups(index, value)
    }
    /**
     * ```
     * All updatable groups present in |partitions| of this DeltaArchiveManifest.
     * - If an updatable group is on the device but not in the manifest, it is
     * not updated. Hence, the group will not be resized, and partitions cannot
     * be added to or removed from the group.
     * - If an updatable group is in the manifest but not on the device, the group
     * is added to the device.
     * ```
     *
     * `repeated .chromeos_update_engine.DynamicPartitionGroup groups = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearGroups")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup, GroupsProxy>.clear() {
      _builder.clearGroups()
    }

    /**
     * ```
     * Whether dynamic partitions have snapshots during the update. If this is
     * set to true, the update_engine daemon creates snapshots for all dynamic
     * partitions if possible. If this is unset, the update_engine daemon MUST
     * NOT create snapshots for dynamic partitions.
     * ```
     *
     * `optional bool snapshot_enabled = 2;`
     */
    public var snapshotEnabled: kotlin.Boolean
      @kotlin.jvm.JvmName("getSnapshotEnabled")
        get() = _builder.snapshotEnabled
      @kotlin.jvm.JvmName("setSnapshotEnabled")
        set(value) {
        _builder.snapshotEnabled = value
      }
    /**
     * ```
     * Whether dynamic partitions have snapshots during the update. If this is
     * set to true, the update_engine daemon creates snapshots for all dynamic
     * partitions if possible. If this is unset, the update_engine daemon MUST
     * NOT create snapshots for dynamic partitions.
     * ```
     *
     * `optional bool snapshot_enabled = 2;`
     */
    public fun clearSnapshotEnabled() {
      _builder.clearSnapshotEnabled()
    }
    /**
     * ```
     * Whether dynamic partitions have snapshots during the update. If this is
     * set to true, the update_engine daemon creates snapshots for all dynamic
     * partitions if possible. If this is unset, the update_engine daemon MUST
     * NOT create snapshots for dynamic partitions.
     * ```
     *
     * `optional bool snapshot_enabled = 2;`
     * @return Whether the snapshotEnabled field is set.
     */
    public fun hasSnapshotEnabled(): kotlin.Boolean {
      return _builder.hasSnapshotEnabled()
    }

    /**
     * ```
     * If this is set to false, update_engine should not use VABC regardless. If
     * this is set to true, update_engine may choose to use VABC if device
     * supports it, but not guaranteed.
     * VABC stands for Virtual AB Compression
     * ```
     *
     * `optional bool vabc_enabled = 3;`
     */
    public var vabcEnabled: kotlin.Boolean
      @kotlin.jvm.JvmName("getVabcEnabled")
        get() = _builder.vabcEnabled
      @kotlin.jvm.JvmName("setVabcEnabled")
        set(value) {
        _builder.vabcEnabled = value
      }
    /**
     * ```
     * If this is set to false, update_engine should not use VABC regardless. If
     * this is set to true, update_engine may choose to use VABC if device
     * supports it, but not guaranteed.
     * VABC stands for Virtual AB Compression
     * ```
     *
     * `optional bool vabc_enabled = 3;`
     */
    public fun clearVabcEnabled() {
      _builder.clearVabcEnabled()
    }
    /**
     * ```
     * If this is set to false, update_engine should not use VABC regardless. If
     * this is set to true, update_engine may choose to use VABC if device
     * supports it, but not guaranteed.
     * VABC stands for Virtual AB Compression
     * ```
     *
     * `optional bool vabc_enabled = 3;`
     * @return Whether the vabcEnabled field is set.
     */
    public fun hasVabcEnabled(): kotlin.Boolean {
      return _builder.hasVabcEnabled()
    }

    /**
     * ```
     * The compression algorithm used by VABC. Available ones are "gz", "brotli".
     * See system/core/fs_mgr/libsnapshot/cow_writer.cpp for available options,
     * as this parameter is ultimated forwarded to libsnapshot's CowWriter
     * ```
     *
     * `optional string vabc_compression_param = 4;`
     */
    public var vabcCompressionParam: kotlin.String
      @kotlin.jvm.JvmName("getVabcCompressionParam")
        get() = _builder.vabcCompressionParam
      @kotlin.jvm.JvmName("setVabcCompressionParam")
        set(value) {
        _builder.vabcCompressionParam = value
      }
    /**
     * ```
     * The compression algorithm used by VABC. Available ones are "gz", "brotli".
     * See system/core/fs_mgr/libsnapshot/cow_writer.cpp for available options,
     * as this parameter is ultimated forwarded to libsnapshot's CowWriter
     * ```
     *
     * `optional string vabc_compression_param = 4;`
     */
    public fun clearVabcCompressionParam() {
      _builder.clearVabcCompressionParam()
    }
    /**
     * ```
     * The compression algorithm used by VABC. Available ones are "gz", "brotli".
     * See system/core/fs_mgr/libsnapshot/cow_writer.cpp for available options,
     * as this parameter is ultimated forwarded to libsnapshot's CowWriter
     * ```
     *
     * `optional string vabc_compression_param = 4;`
     * @return Whether the vabcCompressionParam field is set.
     */
    public fun hasVabcCompressionParam(): kotlin.Boolean {
      return _builder.hasVabcCompressionParam()
    }

    /**
     * ```
     * COW version used by VABC. The represents the major version in the COW
     * header
     * ```
     *
     * `optional uint32 cow_version = 5;`
     */
    public var cowVersion: kotlin.Int
      @kotlin.jvm.JvmName("getCowVersion")
        get() = _builder.cowVersion
      @kotlin.jvm.JvmName("setCowVersion")
        set(value) {
        _builder.cowVersion = value
      }
    /**
     * ```
     * COW version used by VABC. The represents the major version in the COW
     * header
     * ```
     *
     * `optional uint32 cow_version = 5;`
     */
    public fun clearCowVersion() {
      _builder.clearCowVersion()
    }
    /**
     * ```
     * COW version used by VABC. The represents the major version in the COW
     * header
     * ```
     *
     * `optional uint32 cow_version = 5;`
     * @return Whether the cowVersion field is set.
     */
    public fun hasCowVersion(): kotlin.Boolean {
      return _builder.hasCowVersion()
    }

    /**
     * ```
     * A collection of knobs to tune Virtual AB Compression
     * ```
     *
     * `optional .chromeos_update_engine.VABCFeatureSet vabc_feature_set = 6;`
     */
    public var vabcFeatureSet: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.VABCFeatureSet
      @kotlin.jvm.JvmName("getVabcFeatureSet")
        get() = _builder.vabcFeatureSet
      @kotlin.jvm.JvmName("setVabcFeatureSet")
        set(value) {
        _builder.vabcFeatureSet = value
      }
    /**
     * ```
     * A collection of knobs to tune Virtual AB Compression
     * ```
     *
     * `optional .chromeos_update_engine.VABCFeatureSet vabc_feature_set = 6;`
     */
    public fun clearVabcFeatureSet() {
      _builder.clearVabcFeatureSet()
    }
    /**
     * ```
     * A collection of knobs to tune Virtual AB Compression
     * ```
     *
     * `optional .chromeos_update_engine.VABCFeatureSet vabc_feature_set = 6;`
     * @return Whether the vabcFeatureSet field is set.
     */
    public fun hasVabcFeatureSet(): kotlin.Boolean {
      return _builder.hasVabcFeatureSet()
    }

    public val DynamicPartitionMetadataKt.Dsl.vabcFeatureSetOrNull: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.VABCFeatureSet?
      get() = _builder.vabcFeatureSetOrNull

    /**
     * ```
     * Max bytes to be compressed at once during ota. Options: 4k, 8k, 16k, 32k,
     * 64k, 128k
     * ```
     *
     * `optional uint64 compression_factor = 7;`
     */
    public var compressionFactor: kotlin.Long
      @kotlin.jvm.JvmName("getCompressionFactor")
        get() = _builder.compressionFactor
      @kotlin.jvm.JvmName("setCompressionFactor")
        set(value) {
        _builder.compressionFactor = value
      }
    /**
     * ```
     * Max bytes to be compressed at once during ota. Options: 4k, 8k, 16k, 32k,
     * 64k, 128k
     * ```
     *
     * `optional uint64 compression_factor = 7;`
     */
    public fun clearCompressionFactor() {
      _builder.clearCompressionFactor()
    }
    /**
     * ```
     * Max bytes to be compressed at once during ota. Options: 4k, 8k, 16k, 32k,
     * 64k, 128k
     * ```
     *
     * `optional uint64 compression_factor = 7;`
     * @return Whether the compressionFactor field is set.
     */
    public fun hasCompressionFactor(): kotlin.Boolean {
      return _builder.hasCompressionFactor()
    }

    /**
     * ```
     * Whether to disable UBLK for OTA. This will force dm-user as OTA backend
     * choice even if device was configured for UBLK based snapshots.
     * ```
     *
     * `optional bool disable_ublk = 8;`
     */
    public var disableUblk: kotlin.Boolean
      @kotlin.jvm.JvmName("getDisableUblk")
        get() = _builder.disableUblk
      @kotlin.jvm.JvmName("setDisableUblk")
        set(value) {
        _builder.disableUblk = value
      }
    /**
     * ```
     * Whether to disable UBLK for OTA. This will force dm-user as OTA backend
     * choice even if device was configured for UBLK based snapshots.
     * ```
     *
     * `optional bool disable_ublk = 8;`
     */
    public fun clearDisableUblk() {
      _builder.clearDisableUblk()
    }
    /**
     * ```
     * Whether to disable UBLK for OTA. This will force dm-user as OTA backend
     * choice even if device was configured for UBLK based snapshots.
     * ```
     *
     * `optional bool disable_ublk = 8;`
     * @return Whether the disableUblk field is set.
     */
    public fun hasDisableUblk(): kotlin.Boolean {
      return _builder.hasDisableUblk()
    }
  }
}
public inline fun com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionMetadata.copy(block: `com.rajmani7584.payloaddumper.engine.chromeos_update_engine`.DynamicPartitionMetadataKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionMetadata =
  `com.rajmani7584.payloaddumper.engine.chromeos_update_engine`.DynamicPartitionMetadataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.DynamicPartitionMetadataOrBuilder.vabcFeatureSetOrNull: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.VABCFeatureSet?
  get() = if (hasVabcFeatureSet()) getVabcFeatureSet() else null

