// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: update_metadata.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.rajmani7584.payloaddumper.engine.chromeos_update_engine;

@kotlin.jvm.JvmName("-initializeextent")
public inline fun extent(block: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.ExtentKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent =
  com.rajmani7584.payloaddumper.engine.chromeos_update_engine.ExtentKt.Dsl._create(com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `chromeos_update_engine.Extent`
 */
public object ExtentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent = _builder.build()

    /**
     * `optional uint64 start_block = 1;`
     */
    public var startBlock: kotlin.Long
      @kotlin.jvm.JvmName("getStartBlock")
        get() = _builder.startBlock
      @kotlin.jvm.JvmName("setStartBlock")
        set(value) {
        _builder.startBlock = value
      }
    /**
     * `optional uint64 start_block = 1;`
     */
    public fun clearStartBlock() {
      _builder.clearStartBlock()
    }
    /**
     * `optional uint64 start_block = 1;`
     * @return Whether the startBlock field is set.
     */
    public fun hasStartBlock(): kotlin.Boolean {
      return _builder.hasStartBlock()
    }

    /**
     * `optional uint64 num_blocks = 2;`
     */
    public var numBlocks: kotlin.Long
      @kotlin.jvm.JvmName("getNumBlocks")
        get() = _builder.numBlocks
      @kotlin.jvm.JvmName("setNumBlocks")
        set(value) {
        _builder.numBlocks = value
      }
    /**
     * `optional uint64 num_blocks = 2;`
     */
    public fun clearNumBlocks() {
      _builder.clearNumBlocks()
    }
    /**
     * `optional uint64 num_blocks = 2;`
     * @return Whether the numBlocks field is set.
     */
    public fun hasNumBlocks(): kotlin.Boolean {
      return _builder.hasNumBlocks()
    }
  }
}
public inline fun com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent.copy(block: `com.rajmani7584.payloaddumper.engine.chromeos_update_engine`.ExtentKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent =
  `com.rajmani7584.payloaddumper.engine.chromeos_update_engine`.ExtentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

