// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: update_metadata.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.rajmani7584.payloaddumper.engine.chromeos_update_engine;

@kotlin.jvm.JvmName("-initializepartitionUpdate")
public inline fun partitionUpdate(block: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.PartitionUpdateKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionUpdate =
  com.rajmani7584.payloaddumper.engine.chromeos_update_engine.PartitionUpdateKt.Dsl._create(com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionUpdate.newBuilder()).apply { block() }._build()
/**
 * ```
 * Describes the update to apply to a single partition.
 * ```
 *
 * Protobuf type `chromeos_update_engine.PartitionUpdate`
 */
public object PartitionUpdateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionUpdate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionUpdate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionUpdate = _builder.build()

    /**
     * ```
     * A platform-specific name to identify the partition set being updated. For
     * example, in Chrome OS this could be "ROOT" or "KERNEL".
     * ```
     *
     * `required string partition_name = 1;`
     */
    public var partitionName: kotlin.String
      @kotlin.jvm.JvmName("getPartitionName")
        get() = _builder.partitionName
      @kotlin.jvm.JvmName("setPartitionName")
        set(value) {
        _builder.partitionName = value
      }
    /**
     * ```
     * A platform-specific name to identify the partition set being updated. For
     * example, in Chrome OS this could be "ROOT" or "KERNEL".
     * ```
     *
     * `required string partition_name = 1;`
     */
    public fun clearPartitionName() {
      _builder.clearPartitionName()
    }
    /**
     * ```
     * A platform-specific name to identify the partition set being updated. For
     * example, in Chrome OS this could be "ROOT" or "KERNEL".
     * ```
     *
     * `required string partition_name = 1;`
     * @return Whether the partitionName field is set.
     */
    public fun hasPartitionName(): kotlin.Boolean {
      return _builder.hasPartitionName()
    }

    /**
     * ```
     * Whether this partition carries a filesystem with post-install program that
     * must be run to finalize the update process. See also |postinstall_path| and
     * |filesystem_type|.
     * ```
     *
     * `optional bool run_postinstall = 2;`
     */
    public var runPostinstall: kotlin.Boolean
      @kotlin.jvm.JvmName("getRunPostinstall")
        get() = _builder.runPostinstall
      @kotlin.jvm.JvmName("setRunPostinstall")
        set(value) {
        _builder.runPostinstall = value
      }
    /**
     * ```
     * Whether this partition carries a filesystem with post-install program that
     * must be run to finalize the update process. See also |postinstall_path| and
     * |filesystem_type|.
     * ```
     *
     * `optional bool run_postinstall = 2;`
     */
    public fun clearRunPostinstall() {
      _builder.clearRunPostinstall()
    }
    /**
     * ```
     * Whether this partition carries a filesystem with post-install program that
     * must be run to finalize the update process. See also |postinstall_path| and
     * |filesystem_type|.
     * ```
     *
     * `optional bool run_postinstall = 2;`
     * @return Whether the runPostinstall field is set.
     */
    public fun hasRunPostinstall(): kotlin.Boolean {
      return _builder.hasRunPostinstall()
    }

    /**
     * ```
     * The path of the executable program to run during the post-install step,
     * relative to the root of this filesystem. If not set, the default "postinst"
     * will be used. This setting is only used when |run_postinstall| is set and
     * true.
     * ```
     *
     * `optional string postinstall_path = 3;`
     */
    public var postinstallPath: kotlin.String
      @kotlin.jvm.JvmName("getPostinstallPath")
        get() = _builder.postinstallPath
      @kotlin.jvm.JvmName("setPostinstallPath")
        set(value) {
        _builder.postinstallPath = value
      }
    /**
     * ```
     * The path of the executable program to run during the post-install step,
     * relative to the root of this filesystem. If not set, the default "postinst"
     * will be used. This setting is only used when |run_postinstall| is set and
     * true.
     * ```
     *
     * `optional string postinstall_path = 3;`
     */
    public fun clearPostinstallPath() {
      _builder.clearPostinstallPath()
    }
    /**
     * ```
     * The path of the executable program to run during the post-install step,
     * relative to the root of this filesystem. If not set, the default "postinst"
     * will be used. This setting is only used when |run_postinstall| is set and
     * true.
     * ```
     *
     * `optional string postinstall_path = 3;`
     * @return Whether the postinstallPath field is set.
     */
    public fun hasPostinstallPath(): kotlin.Boolean {
      return _builder.hasPostinstallPath()
    }

    /**
     * ```
     * The filesystem type as passed to the mount(2) syscall when mounting the new
     * filesystem to run the post-install program. If not set, a fixed list of
     * filesystems will be attempted. This setting is only used if
     * |run_postinstall| is set and true.
     * ```
     *
     * `optional string filesystem_type = 4;`
     */
    public var filesystemType: kotlin.String
      @kotlin.jvm.JvmName("getFilesystemType")
        get() = _builder.filesystemType
      @kotlin.jvm.JvmName("setFilesystemType")
        set(value) {
        _builder.filesystemType = value
      }
    /**
     * ```
     * The filesystem type as passed to the mount(2) syscall when mounting the new
     * filesystem to run the post-install program. If not set, a fixed list of
     * filesystems will be attempted. This setting is only used if
     * |run_postinstall| is set and true.
     * ```
     *
     * `optional string filesystem_type = 4;`
     */
    public fun clearFilesystemType() {
      _builder.clearFilesystemType()
    }
    /**
     * ```
     * The filesystem type as passed to the mount(2) syscall when mounting the new
     * filesystem to run the post-install program. If not set, a fixed list of
     * filesystems will be attempted. This setting is only used if
     * |run_postinstall| is set and true.
     * ```
     *
     * `optional string filesystem_type = 4;`
     * @return Whether the filesystemType field is set.
     */
    public fun hasFilesystemType(): kotlin.Boolean {
      return _builder.hasFilesystemType()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class NewPartitionSignatureProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * If present, a list of signatures of the new_partition_info.hash signed with
     * different keys. If the update_engine daemon requires vendor-signed images
     * and has its public key installed, one of the signatures should be valid
     * for /postinstall to run.
     * ```
     *
     * `repeated .chromeos_update_engine.Signatures.Signature new_partition_signature = 5;`
     */
     public val newPartitionSignature: com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature, NewPartitionSignatureProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.newPartitionSignatureList
      )
    /**
     * ```
     * If present, a list of signatures of the new_partition_info.hash signed with
     * different keys. If the update_engine daemon requires vendor-signed images
     * and has its public key installed, one of the signatures should be valid
     * for /postinstall to run.
     * ```
     *
     * `repeated .chromeos_update_engine.Signatures.Signature new_partition_signature = 5;`
     * @param value The newPartitionSignature to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addNewPartitionSignature")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature, NewPartitionSignatureProxy>.add(value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature) {
      _builder.addNewPartitionSignature(value)
    }
    /**
     * ```
     * If present, a list of signatures of the new_partition_info.hash signed with
     * different keys. If the update_engine daemon requires vendor-signed images
     * and has its public key installed, one of the signatures should be valid
     * for /postinstall to run.
     * ```
     *
     * `repeated .chromeos_update_engine.Signatures.Signature new_partition_signature = 5;`
     * @param value The newPartitionSignature to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignNewPartitionSignature")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature, NewPartitionSignatureProxy>.plusAssign(value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature) {
      add(value)
    }
    /**
     * ```
     * If present, a list of signatures of the new_partition_info.hash signed with
     * different keys. If the update_engine daemon requires vendor-signed images
     * and has its public key installed, one of the signatures should be valid
     * for /postinstall to run.
     * ```
     *
     * `repeated .chromeos_update_engine.Signatures.Signature new_partition_signature = 5;`
     * @param values The newPartitionSignature to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllNewPartitionSignature")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature, NewPartitionSignatureProxy>.addAll(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature>) {
      _builder.addAllNewPartitionSignature(values)
    }
    /**
     * ```
     * If present, a list of signatures of the new_partition_info.hash signed with
     * different keys. If the update_engine daemon requires vendor-signed images
     * and has its public key installed, one of the signatures should be valid
     * for /postinstall to run.
     * ```
     *
     * `repeated .chromeos_update_engine.Signatures.Signature new_partition_signature = 5;`
     * @param values The newPartitionSignature to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllNewPartitionSignature")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature, NewPartitionSignatureProxy>.plusAssign(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature>) {
      addAll(values)
    }
    /**
     * ```
     * If present, a list of signatures of the new_partition_info.hash signed with
     * different keys. If the update_engine daemon requires vendor-signed images
     * and has its public key installed, one of the signatures should be valid
     * for /postinstall to run.
     * ```
     *
     * `repeated .chromeos_update_engine.Signatures.Signature new_partition_signature = 5;`
     * @param index The index to set the value at.
     * @param value The newPartitionSignature to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setNewPartitionSignature")
    public operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature, NewPartitionSignatureProxy>.set(index: kotlin.Int, value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature) {
      _builder.setNewPartitionSignature(index, value)
    }
    /**
     * ```
     * If present, a list of signatures of the new_partition_info.hash signed with
     * different keys. If the update_engine daemon requires vendor-signed images
     * and has its public key installed, one of the signatures should be valid
     * for /postinstall to run.
     * ```
     *
     * `repeated .chromeos_update_engine.Signatures.Signature new_partition_signature = 5;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearNewPartitionSignature")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature, NewPartitionSignatureProxy>.clear() {
      _builder.clearNewPartitionSignature()
    }

    /**
     * `optional .chromeos_update_engine.PartitionInfo old_partition_info = 6;`
     */
    public var oldPartitionInfo: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionInfo
      @kotlin.jvm.JvmName("getOldPartitionInfo")
        get() = _builder.oldPartitionInfo
      @kotlin.jvm.JvmName("setOldPartitionInfo")
        set(value) {
        _builder.oldPartitionInfo = value
      }
    /**
     * `optional .chromeos_update_engine.PartitionInfo old_partition_info = 6;`
     */
    public fun clearOldPartitionInfo() {
      _builder.clearOldPartitionInfo()
    }
    /**
     * `optional .chromeos_update_engine.PartitionInfo old_partition_info = 6;`
     * @return Whether the oldPartitionInfo field is set.
     */
    public fun hasOldPartitionInfo(): kotlin.Boolean {
      return _builder.hasOldPartitionInfo()
    }

    public val PartitionUpdateKt.Dsl.oldPartitionInfoOrNull: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionInfo?
      get() = _builder.oldPartitionInfoOrNull

    /**
     * `optional .chromeos_update_engine.PartitionInfo new_partition_info = 7;`
     */
    public var newPartitionInfo: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionInfo
      @kotlin.jvm.JvmName("getNewPartitionInfo")
        get() = _builder.newPartitionInfo
      @kotlin.jvm.JvmName("setNewPartitionInfo")
        set(value) {
        _builder.newPartitionInfo = value
      }
    /**
     * `optional .chromeos_update_engine.PartitionInfo new_partition_info = 7;`
     */
    public fun clearNewPartitionInfo() {
      _builder.clearNewPartitionInfo()
    }
    /**
     * `optional .chromeos_update_engine.PartitionInfo new_partition_info = 7;`
     * @return Whether the newPartitionInfo field is set.
     */
    public fun hasNewPartitionInfo(): kotlin.Boolean {
      return _builder.hasNewPartitionInfo()
    }

    public val PartitionUpdateKt.Dsl.newPartitionInfoOrNull: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionInfo?
      get() = _builder.newPartitionInfoOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OperationsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * The list of operations to be performed to apply this PartitionUpdate. The
     * associated operation blobs (in operations[i].data_offset, data_length)
     * should be stored contiguously and in the same order.
     * ```
     *
     * `repeated .chromeos_update_engine.InstallOperation operations = 8;`
     */
     public val operations: com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.InstallOperation, OperationsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.operationsList
      )
    /**
     * ```
     * The list of operations to be performed to apply this PartitionUpdate. The
     * associated operation blobs (in operations[i].data_offset, data_length)
     * should be stored contiguously and in the same order.
     * ```
     *
     * `repeated .chromeos_update_engine.InstallOperation operations = 8;`
     * @param value The operations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addOperations")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.InstallOperation, OperationsProxy>.add(value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.InstallOperation) {
      _builder.addOperations(value)
    }
    /**
     * ```
     * The list of operations to be performed to apply this PartitionUpdate. The
     * associated operation blobs (in operations[i].data_offset, data_length)
     * should be stored contiguously and in the same order.
     * ```
     *
     * `repeated .chromeos_update_engine.InstallOperation operations = 8;`
     * @param value The operations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignOperations")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.InstallOperation, OperationsProxy>.plusAssign(value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.InstallOperation) {
      add(value)
    }
    /**
     * ```
     * The list of operations to be performed to apply this PartitionUpdate. The
     * associated operation blobs (in operations[i].data_offset, data_length)
     * should be stored contiguously and in the same order.
     * ```
     *
     * `repeated .chromeos_update_engine.InstallOperation operations = 8;`
     * @param values The operations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllOperations")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.InstallOperation, OperationsProxy>.addAll(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.InstallOperation>) {
      _builder.addAllOperations(values)
    }
    /**
     * ```
     * The list of operations to be performed to apply this PartitionUpdate. The
     * associated operation blobs (in operations[i].data_offset, data_length)
     * should be stored contiguously and in the same order.
     * ```
     *
     * `repeated .chromeos_update_engine.InstallOperation operations = 8;`
     * @param values The operations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllOperations")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.InstallOperation, OperationsProxy>.plusAssign(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.InstallOperation>) {
      addAll(values)
    }
    /**
     * ```
     * The list of operations to be performed to apply this PartitionUpdate. The
     * associated operation blobs (in operations[i].data_offset, data_length)
     * should be stored contiguously and in the same order.
     * ```
     *
     * `repeated .chromeos_update_engine.InstallOperation operations = 8;`
     * @param index The index to set the value at.
     * @param value The operations to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setOperations")
    public operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.InstallOperation, OperationsProxy>.set(index: kotlin.Int, value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.InstallOperation) {
      _builder.setOperations(index, value)
    }
    /**
     * ```
     * The list of operations to be performed to apply this PartitionUpdate. The
     * associated operation blobs (in operations[i].data_offset, data_length)
     * should be stored contiguously and in the same order.
     * ```
     *
     * `repeated .chromeos_update_engine.InstallOperation operations = 8;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearOperations")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.InstallOperation, OperationsProxy>.clear() {
      _builder.clearOperations()
    }

    /**
     * ```
     * Whether a failure in the postinstall step for this partition should be
     * ignored.
     * ```
     *
     * `optional bool postinstall_optional = 9;`
     */
    public var postinstallOptional: kotlin.Boolean
      @kotlin.jvm.JvmName("getPostinstallOptional")
        get() = _builder.postinstallOptional
      @kotlin.jvm.JvmName("setPostinstallOptional")
        set(value) {
        _builder.postinstallOptional = value
      }
    /**
     * ```
     * Whether a failure in the postinstall step for this partition should be
     * ignored.
     * ```
     *
     * `optional bool postinstall_optional = 9;`
     */
    public fun clearPostinstallOptional() {
      _builder.clearPostinstallOptional()
    }
    /**
     * ```
     * Whether a failure in the postinstall step for this partition should be
     * ignored.
     * ```
     *
     * `optional bool postinstall_optional = 9;`
     * @return Whether the postinstallOptional field is set.
     */
    public fun hasPostinstallOptional(): kotlin.Boolean {
      return _builder.hasPostinstallOptional()
    }

    /**
     * ```
     * The extent for data covered by verity hash tree.
     * ```
     *
     * `optional .chromeos_update_engine.Extent hash_tree_data_extent = 10;`
     */
    public var hashTreeDataExtent: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent
      @kotlin.jvm.JvmName("getHashTreeDataExtent")
        get() = _builder.hashTreeDataExtent
      @kotlin.jvm.JvmName("setHashTreeDataExtent")
        set(value) {
        _builder.hashTreeDataExtent = value
      }
    /**
     * ```
     * The extent for data covered by verity hash tree.
     * ```
     *
     * `optional .chromeos_update_engine.Extent hash_tree_data_extent = 10;`
     */
    public fun clearHashTreeDataExtent() {
      _builder.clearHashTreeDataExtent()
    }
    /**
     * ```
     * The extent for data covered by verity hash tree.
     * ```
     *
     * `optional .chromeos_update_engine.Extent hash_tree_data_extent = 10;`
     * @return Whether the hashTreeDataExtent field is set.
     */
    public fun hasHashTreeDataExtent(): kotlin.Boolean {
      return _builder.hasHashTreeDataExtent()
    }

    public val PartitionUpdateKt.Dsl.hashTreeDataExtentOrNull: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent?
      get() = _builder.hashTreeDataExtentOrNull

    /**
     * ```
     * The extent to store verity hash tree.
     * ```
     *
     * `optional .chromeos_update_engine.Extent hash_tree_extent = 11;`
     */
    public var hashTreeExtent: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent
      @kotlin.jvm.JvmName("getHashTreeExtent")
        get() = _builder.hashTreeExtent
      @kotlin.jvm.JvmName("setHashTreeExtent")
        set(value) {
        _builder.hashTreeExtent = value
      }
    /**
     * ```
     * The extent to store verity hash tree.
     * ```
     *
     * `optional .chromeos_update_engine.Extent hash_tree_extent = 11;`
     */
    public fun clearHashTreeExtent() {
      _builder.clearHashTreeExtent()
    }
    /**
     * ```
     * The extent to store verity hash tree.
     * ```
     *
     * `optional .chromeos_update_engine.Extent hash_tree_extent = 11;`
     * @return Whether the hashTreeExtent field is set.
     */
    public fun hasHashTreeExtent(): kotlin.Boolean {
      return _builder.hasHashTreeExtent()
    }

    public val PartitionUpdateKt.Dsl.hashTreeExtentOrNull: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent?
      get() = _builder.hashTreeExtentOrNull

    /**
     * ```
     * The hash algorithm used in verity hash tree.
     * ```
     *
     * `optional string hash_tree_algorithm = 12;`
     */
    public var hashTreeAlgorithm: kotlin.String
      @kotlin.jvm.JvmName("getHashTreeAlgorithm")
        get() = _builder.hashTreeAlgorithm
      @kotlin.jvm.JvmName("setHashTreeAlgorithm")
        set(value) {
        _builder.hashTreeAlgorithm = value
      }
    /**
     * ```
     * The hash algorithm used in verity hash tree.
     * ```
     *
     * `optional string hash_tree_algorithm = 12;`
     */
    public fun clearHashTreeAlgorithm() {
      _builder.clearHashTreeAlgorithm()
    }
    /**
     * ```
     * The hash algorithm used in verity hash tree.
     * ```
     *
     * `optional string hash_tree_algorithm = 12;`
     * @return Whether the hashTreeAlgorithm field is set.
     */
    public fun hasHashTreeAlgorithm(): kotlin.Boolean {
      return _builder.hasHashTreeAlgorithm()
    }

    /**
     * ```
     * The salt used for verity hash tree.
     * ```
     *
     * `optional bytes hash_tree_salt = 13;`
     */
    public var hashTreeSalt: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getHashTreeSalt")
        get() = _builder.hashTreeSalt
      @kotlin.jvm.JvmName("setHashTreeSalt")
        set(value) {
        _builder.hashTreeSalt = value
      }
    /**
     * ```
     * The salt used for verity hash tree.
     * ```
     *
     * `optional bytes hash_tree_salt = 13;`
     */
    public fun clearHashTreeSalt() {
      _builder.clearHashTreeSalt()
    }
    /**
     * ```
     * The salt used for verity hash tree.
     * ```
     *
     * `optional bytes hash_tree_salt = 13;`
     * @return Whether the hashTreeSalt field is set.
     */
    public fun hasHashTreeSalt(): kotlin.Boolean {
      return _builder.hasHashTreeSalt()
    }

    /**
     * ```
     * The extent for data covered by FEC.
     * ```
     *
     * `optional .chromeos_update_engine.Extent fec_data_extent = 14;`
     */
    public var fecDataExtent: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent
      @kotlin.jvm.JvmName("getFecDataExtent")
        get() = _builder.fecDataExtent
      @kotlin.jvm.JvmName("setFecDataExtent")
        set(value) {
        _builder.fecDataExtent = value
      }
    /**
     * ```
     * The extent for data covered by FEC.
     * ```
     *
     * `optional .chromeos_update_engine.Extent fec_data_extent = 14;`
     */
    public fun clearFecDataExtent() {
      _builder.clearFecDataExtent()
    }
    /**
     * ```
     * The extent for data covered by FEC.
     * ```
     *
     * `optional .chromeos_update_engine.Extent fec_data_extent = 14;`
     * @return Whether the fecDataExtent field is set.
     */
    public fun hasFecDataExtent(): kotlin.Boolean {
      return _builder.hasFecDataExtent()
    }

    public val PartitionUpdateKt.Dsl.fecDataExtentOrNull: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent?
      get() = _builder.fecDataExtentOrNull

    /**
     * ```
     * The extent to store FEC.
     * ```
     *
     * `optional .chromeos_update_engine.Extent fec_extent = 15;`
     */
    public var fecExtent: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent
      @kotlin.jvm.JvmName("getFecExtent")
        get() = _builder.fecExtent
      @kotlin.jvm.JvmName("setFecExtent")
        set(value) {
        _builder.fecExtent = value
      }
    /**
     * ```
     * The extent to store FEC.
     * ```
     *
     * `optional .chromeos_update_engine.Extent fec_extent = 15;`
     */
    public fun clearFecExtent() {
      _builder.clearFecExtent()
    }
    /**
     * ```
     * The extent to store FEC.
     * ```
     *
     * `optional .chromeos_update_engine.Extent fec_extent = 15;`
     * @return Whether the fecExtent field is set.
     */
    public fun hasFecExtent(): kotlin.Boolean {
      return _builder.hasFecExtent()
    }

    public val PartitionUpdateKt.Dsl.fecExtentOrNull: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent?
      get() = _builder.fecExtentOrNull

    /**
     * ```
     * The number of FEC roots.
     * ```
     *
     * `optional uint32 fec_roots = 16 [default = 2];`
     */
    public var fecRoots: kotlin.Int
      @kotlin.jvm.JvmName("getFecRoots")
        get() = _builder.fecRoots
      @kotlin.jvm.JvmName("setFecRoots")
        set(value) {
        _builder.fecRoots = value
      }
    /**
     * ```
     * The number of FEC roots.
     * ```
     *
     * `optional uint32 fec_roots = 16 [default = 2];`
     */
    public fun clearFecRoots() {
      _builder.clearFecRoots()
    }
    /**
     * ```
     * The number of FEC roots.
     * ```
     *
     * `optional uint32 fec_roots = 16 [default = 2];`
     * @return Whether the fecRoots field is set.
     */
    public fun hasFecRoots(): kotlin.Boolean {
      return _builder.hasFecRoots()
    }

    /**
     * ```
     * Per-partition version used for downgrade detection, added
     * as an effort to support partial updates. For most partitions,
     * this is the build timestamp.
     * ```
     *
     * `optional string version = 17;`
     */
    public var version: kotlin.String
      @kotlin.jvm.JvmName("getVersion")
        get() = _builder.version
      @kotlin.jvm.JvmName("setVersion")
        set(value) {
        _builder.version = value
      }
    /**
     * ```
     * Per-partition version used for downgrade detection, added
     * as an effort to support partial updates. For most partitions,
     * this is the build timestamp.
     * ```
     *
     * `optional string version = 17;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }
    /**
     * ```
     * Per-partition version used for downgrade detection, added
     * as an effort to support partial updates. For most partitions,
     * this is the build timestamp.
     * ```
     *
     * `optional string version = 17;`
     * @return Whether the version field is set.
     */
    public fun hasVersion(): kotlin.Boolean {
      return _builder.hasVersion()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MergeOperationsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * A sorted list of CowMergeOperation. When writing cow, we can choose to
     * skip writing the raw bytes for these extents. During snapshot merge, the
     * bytes will read from the source partitions instead.
     * ```
     *
     * `repeated .chromeos_update_engine.CowMergeOperation merge_operations = 18;`
     */
     public val mergeOperations: com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.CowMergeOperation, MergeOperationsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.mergeOperationsList
      )
    /**
     * ```
     * A sorted list of CowMergeOperation. When writing cow, we can choose to
     * skip writing the raw bytes for these extents. During snapshot merge, the
     * bytes will read from the source partitions instead.
     * ```
     *
     * `repeated .chromeos_update_engine.CowMergeOperation merge_operations = 18;`
     * @param value The mergeOperations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addMergeOperations")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.CowMergeOperation, MergeOperationsProxy>.add(value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.CowMergeOperation) {
      _builder.addMergeOperations(value)
    }
    /**
     * ```
     * A sorted list of CowMergeOperation. When writing cow, we can choose to
     * skip writing the raw bytes for these extents. During snapshot merge, the
     * bytes will read from the source partitions instead.
     * ```
     *
     * `repeated .chromeos_update_engine.CowMergeOperation merge_operations = 18;`
     * @param value The mergeOperations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignMergeOperations")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.CowMergeOperation, MergeOperationsProxy>.plusAssign(value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.CowMergeOperation) {
      add(value)
    }
    /**
     * ```
     * A sorted list of CowMergeOperation. When writing cow, we can choose to
     * skip writing the raw bytes for these extents. During snapshot merge, the
     * bytes will read from the source partitions instead.
     * ```
     *
     * `repeated .chromeos_update_engine.CowMergeOperation merge_operations = 18;`
     * @param values The mergeOperations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllMergeOperations")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.CowMergeOperation, MergeOperationsProxy>.addAll(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.CowMergeOperation>) {
      _builder.addAllMergeOperations(values)
    }
    /**
     * ```
     * A sorted list of CowMergeOperation. When writing cow, we can choose to
     * skip writing the raw bytes for these extents. During snapshot merge, the
     * bytes will read from the source partitions instead.
     * ```
     *
     * `repeated .chromeos_update_engine.CowMergeOperation merge_operations = 18;`
     * @param values The mergeOperations to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllMergeOperations")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.CowMergeOperation, MergeOperationsProxy>.plusAssign(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.CowMergeOperation>) {
      addAll(values)
    }
    /**
     * ```
     * A sorted list of CowMergeOperation. When writing cow, we can choose to
     * skip writing the raw bytes for these extents. During snapshot merge, the
     * bytes will read from the source partitions instead.
     * ```
     *
     * `repeated .chromeos_update_engine.CowMergeOperation merge_operations = 18;`
     * @param index The index to set the value at.
     * @param value The mergeOperations to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setMergeOperations")
    public operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.CowMergeOperation, MergeOperationsProxy>.set(index: kotlin.Int, value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.CowMergeOperation) {
      _builder.setMergeOperations(index, value)
    }
    /**
     * ```
     * A sorted list of CowMergeOperation. When writing cow, we can choose to
     * skip writing the raw bytes for these extents. During snapshot merge, the
     * bytes will read from the source partitions instead.
     * ```
     *
     * `repeated .chromeos_update_engine.CowMergeOperation merge_operations = 18;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearMergeOperations")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.CowMergeOperation, MergeOperationsProxy>.clear() {
      _builder.clearMergeOperations()
    }

    /**
     * ```
     * Estimated size for COW image. This is used by libsnapshot
     * as a hint. If set to 0, libsnapshot should use alternative
     * methods for estimating size.
     * ```
     *
     * `optional uint64 estimate_cow_size = 19;`
     */
    public var estimateCowSize: kotlin.Long
      @kotlin.jvm.JvmName("getEstimateCowSize")
        get() = _builder.estimateCowSize
      @kotlin.jvm.JvmName("setEstimateCowSize")
        set(value) {
        _builder.estimateCowSize = value
      }
    /**
     * ```
     * Estimated size for COW image. This is used by libsnapshot
     * as a hint. If set to 0, libsnapshot should use alternative
     * methods for estimating size.
     * ```
     *
     * `optional uint64 estimate_cow_size = 19;`
     */
    public fun clearEstimateCowSize() {
      _builder.clearEstimateCowSize()
    }
    /**
     * ```
     * Estimated size for COW image. This is used by libsnapshot
     * as a hint. If set to 0, libsnapshot should use alternative
     * methods for estimating size.
     * ```
     *
     * `optional uint64 estimate_cow_size = 19;`
     * @return Whether the estimateCowSize field is set.
     */
    public fun hasEstimateCowSize(): kotlin.Boolean {
      return _builder.hasEstimateCowSize()
    }

    /**
     * ```
     * Information about the cow used by Cow Writer to specify
     * number of cow operations to be written
     * ```
     *
     * `optional uint64 estimate_op_count_max = 20;`
     */
    public var estimateOpCountMax: kotlin.Long
      @kotlin.jvm.JvmName("getEstimateOpCountMax")
        get() = _builder.estimateOpCountMax
      @kotlin.jvm.JvmName("setEstimateOpCountMax")
        set(value) {
        _builder.estimateOpCountMax = value
      }
    /**
     * ```
     * Information about the cow used by Cow Writer to specify
     * number of cow operations to be written
     * ```
     *
     * `optional uint64 estimate_op_count_max = 20;`
     */
    public fun clearEstimateOpCountMax() {
      _builder.clearEstimateOpCountMax()
    }
    /**
     * ```
     * Information about the cow used by Cow Writer to specify
     * number of cow operations to be written
     * ```
     *
     * `optional uint64 estimate_op_count_max = 20;`
     * @return Whether the estimateOpCountMax field is set.
     */
    public fun hasEstimateOpCountMax(): kotlin.Boolean {
      return _builder.hasEstimateOpCountMax()
    }
  }
}
public inline fun com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionUpdate.copy(block: `com.rajmani7584.payloaddumper.engine.chromeos_update_engine`.PartitionUpdateKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionUpdate =
  `com.rajmani7584.payloaddumper.engine.chromeos_update_engine`.PartitionUpdateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionUpdateOrBuilder.oldPartitionInfoOrNull: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionInfo?
  get() = if (hasOldPartitionInfo()) getOldPartitionInfo() else null

public val com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionUpdateOrBuilder.newPartitionInfoOrNull: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionInfo?
  get() = if (hasNewPartitionInfo()) getNewPartitionInfo() else null

public val com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionUpdateOrBuilder.hashTreeDataExtentOrNull: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent?
  get() = if (hasHashTreeDataExtent()) getHashTreeDataExtent() else null

public val com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionUpdateOrBuilder.hashTreeExtentOrNull: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent?
  get() = if (hasHashTreeExtent()) getHashTreeExtent() else null

public val com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionUpdateOrBuilder.fecDataExtentOrNull: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent?
  get() = if (hasFecDataExtent()) getFecDataExtent() else null

public val com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.PartitionUpdateOrBuilder.fecExtentOrNull: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Extent?
  get() = if (hasFecExtent()) getFecExtent() else null

