// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: update_metadata.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.rajmani7584.payloaddumper.engine.chromeos_update_engine;

@kotlin.jvm.JvmName("-initializesignatures")
public inline fun signatures(block: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.SignaturesKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures =
  com.rajmani7584.payloaddumper.engine.chromeos_update_engine.SignaturesKt.Dsl._create(com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `chromeos_update_engine.Signatures`
 */
public object SignaturesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SignaturesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .chromeos_update_engine.Signatures.Signature signatures = 1;`
     */
     public val signatures: com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature, SignaturesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.signaturesList
      )
    /**
     * `repeated .chromeos_update_engine.Signatures.Signature signatures = 1;`
     * @param value The signatures to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addSignatures")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature, SignaturesProxy>.add(value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature) {
      _builder.addSignatures(value)
    }
    /**
     * `repeated .chromeos_update_engine.Signatures.Signature signatures = 1;`
     * @param value The signatures to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignSignatures")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature, SignaturesProxy>.plusAssign(value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature) {
      add(value)
    }
    /**
     * `repeated .chromeos_update_engine.Signatures.Signature signatures = 1;`
     * @param values The signatures to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllSignatures")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature, SignaturesProxy>.addAll(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature>) {
      _builder.addAllSignatures(values)
    }
    /**
     * `repeated .chromeos_update_engine.Signatures.Signature signatures = 1;`
     * @param values The signatures to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllSignatures")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature, SignaturesProxy>.plusAssign(values: kotlin.collections.Iterable<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature>) {
      addAll(values)
    }
    /**
     * `repeated .chromeos_update_engine.Signatures.Signature signatures = 1;`
     * @param index The index to set the value at.
     * @param value The signatures to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setSignatures")
    public operator fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature, SignaturesProxy>.set(index: kotlin.Int, value: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature) {
      _builder.setSignatures(index, value)
    }
    /**
     * `repeated .chromeos_update_engine.Signatures.Signature signatures = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearSignatures")
    public fun com.google.protobuf.kotlin.DslList<com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature, SignaturesProxy>.clear() {
      _builder.clearSignatures()
    }
  }
  @kotlin.jvm.JvmName("-initializesignature")
  public inline fun signature(block: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.SignaturesKt.SignatureKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature =
    com.rajmani7584.payloaddumper.engine.chromeos_update_engine.SignaturesKt.SignatureKt.Dsl._create(com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `chromeos_update_engine.Signatures.Signature`
   */
  public object SignatureKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature = _builder.build()

      /**
       * `optional uint32 version = 1 [deprecated = true];`
       */
      @kotlin.Deprecated(message = "Field version is deprecated") public var version: kotlin.Int
        @kotlin.jvm.JvmName("getVersion")
          get() = _builder.version
        @kotlin.jvm.JvmName("setVersion")
          set(value) {
          _builder.version = value
        }
      /**
       * `optional uint32 version = 1 [deprecated = true];`
       */
      public fun clearVersion() {
        _builder.clearVersion()
      }
      /**
       * `optional uint32 version = 1 [deprecated = true];`
       * @return Whether the version field is set.
       */
      public fun hasVersion(): kotlin.Boolean {
        return _builder.hasVersion()
      }

      /**
       * `optional bytes data = 2;`
       */
      public var data: com.google.protobuf.ByteString
        @kotlin.jvm.JvmName("getData")
          get() = _builder.data
        @kotlin.jvm.JvmName("setData")
          set(value) {
          _builder.data = value
        }
      /**
       * `optional bytes data = 2;`
       */
      public fun clearData() {
        _builder.clearData()
      }
      /**
       * `optional bytes data = 2;`
       * @return Whether the data field is set.
       */
      public fun hasData(): kotlin.Boolean {
        return _builder.hasData()
      }

      /**
       * ```
       * The DER encoded signature size of EC keys is nondeterministic for
       * different input of sha256 hash. However, we need the size of the
       * serialized signatures protobuf string to be fixed before signing;
       * because this size is part of the content to be signed. Therefore, we
       * always pad the signature data to the maximum possible signature size of
       * a given key. And the payload verifier will truncate the signature to
       * its correct size based on the value of |unpadded_signature_size|.
       * ```
       *
       * `optional fixed32 unpadded_signature_size = 3;`
       */
      public var unpaddedSignatureSize: kotlin.Int
        @kotlin.jvm.JvmName("getUnpaddedSignatureSize")
          get() = _builder.unpaddedSignatureSize
        @kotlin.jvm.JvmName("setUnpaddedSignatureSize")
          set(value) {
          _builder.unpaddedSignatureSize = value
        }
      /**
       * ```
       * The DER encoded signature size of EC keys is nondeterministic for
       * different input of sha256 hash. However, we need the size of the
       * serialized signatures protobuf string to be fixed before signing;
       * because this size is part of the content to be signed. Therefore, we
       * always pad the signature data to the maximum possible signature size of
       * a given key. And the payload verifier will truncate the signature to
       * its correct size based on the value of |unpadded_signature_size|.
       * ```
       *
       * `optional fixed32 unpadded_signature_size = 3;`
       */
      public fun clearUnpaddedSignatureSize() {
        _builder.clearUnpaddedSignatureSize()
      }
      /**
       * ```
       * The DER encoded signature size of EC keys is nondeterministic for
       * different input of sha256 hash. However, we need the size of the
       * serialized signatures protobuf string to be fixed before signing;
       * because this size is part of the content to be signed. Therefore, we
       * always pad the signature data to the maximum possible signature size of
       * a given key. And the payload verifier will truncate the signature to
       * its correct size based on the value of |unpadded_signature_size|.
       * ```
       *
       * `optional fixed32 unpadded_signature_size = 3;`
       * @return Whether the unpaddedSignatureSize field is set.
       */
      public fun hasUnpaddedSignatureSize(): kotlin.Boolean {
        return _builder.hasUnpaddedSignatureSize()
      }
    }
  }
}
public inline fun com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.copy(block: `com.rajmani7584.payloaddumper.engine.chromeos_update_engine`.SignaturesKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures =
  `com.rajmani7584.payloaddumper.engine.chromeos_update_engine`.SignaturesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature.copy(block: `com.rajmani7584.payloaddumper.engine.chromeos_update_engine`.SignaturesKt.SignatureKt.Dsl.() -> kotlin.Unit): com.rajmani7584.payloaddumper.engine.chromeos_update_engine.UpdateMetadata.Signatures.Signature =
  `com.rajmani7584.payloaddumper.engine.chromeos_update_engine`.SignaturesKt.SignatureKt.Dsl._create(this.toBuilder()).apply { block() }._build()

