// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PartManifest {
    #[prost(message, repeated, tag = "2")]
    pub partitions: ::prost::alloc::vec::Vec<UpdateInfo>,
    #[prost(uint32, optional, tag = "3")]
    pub block_size: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateInfo {
    #[prost(string, required, tag = "1")]
    pub partition_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub new_partition_info: ::core::option::Option<PartInfo>,
    #[prost(message, repeated, tag = "3")]
    pub operations: ::prost::alloc::vec::Vec<Operation>,
    #[prost(bool, required, tag = "4")]
    pub incremental: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartInfo {
    #[prost(uint64, optional, tag = "1")]
    pub size: ::core::option::Option<u64>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Operation {
    #[prost(uint64, optional, tag = "1")]
    pub data_offset: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "2")]
    pub data_length: ::core::option::Option<u64>,
    #[prost(string, required, tag = "3")]
    pub sha_hash: ::prost::alloc::string::String,
    #[prost(enumeration = "operation::Type", required, tag = "4")]
    pub r#type: i32,
    #[prost(message, repeated, tag = "5")]
    pub dst_extents: ::prost::alloc::vec::Vec<DstExtent>,
}
/// Nested message and enum types in `Operation`.
pub mod operation {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        /// Replace destination extents w/ attached data.
        Replace = 0,
        /// Replace destination extents w/ attached bzipped data.
        ReplaceBz = 1,
        /// Move source extents to target extents.
        #[deprecated]
        Move = 2,
        /// The data is a bsdiff binary diff.
        #[deprecated]
        Bsdiff = 3,
        /// On minor version 2 or newer, these operations are supported:
        ///
        /// Copy from source to target partition
        SourceCopy = 4,
        /// Like BSDIFF, but read from source partition
        SourceBsdiff = 5,
        /// On minor version 3 or newer and on major version 2 or newer, these
        /// operations are supported:
        ///
        /// Replace destination extents w/ attached xz data.
        ReplaceXz = 8,
        /// On minor version 4 or newer, these operations are supported:
        ///
        /// Write zeros in the destination.
        Zero = 6,
        /// Discard the destination blocks, reading as undefined.
        Discard = 7,
        /// Like SOURCE_BSDIFF, but compressed with brotli.
        BrotliBsdiff = 10,
        /// On minor version 5 or newer, these operations are supported:
        ///
        /// The data is in puffdiff format.
        Puffdiff = 9,
        /// On minor version 8 or newer, these operations are supported:
        Zucchini = 11,
        /// On minor version 9 or newer, these operations are supported:
        Lz4diffBsdiff = 12,
        Lz4diffPuffdiff = 13,
        /// On minor version 10 or newer, these operations are supported:
        ReplaceZstd = 14,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Replace => "REPLACE",
                Self::ReplaceBz => "REPLACE_BZ",
                #[allow(deprecated)]
                Self::Move => "MOVE",
                #[allow(deprecated)]
                Self::Bsdiff => "BSDIFF",
                Self::SourceCopy => "SOURCE_COPY",
                Self::SourceBsdiff => "SOURCE_BSDIFF",
                Self::ReplaceXz => "REPLACE_XZ",
                Self::Zero => "ZERO",
                Self::Discard => "DISCARD",
                Self::BrotliBsdiff => "BROTLI_BSDIFF",
                Self::Puffdiff => "PUFFDIFF",
                Self::Zucchini => "ZUCCHINI",
                Self::Lz4diffBsdiff => "LZ4DIFF_BSDIFF",
                Self::Lz4diffPuffdiff => "LZ4DIFF_PUFFDIFF",
                Self::ReplaceZstd => "REPLACE_ZSTD",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "REPLACE" => Some(Self::Replace),
                "REPLACE_BZ" => Some(Self::ReplaceBz),
                "MOVE" => Some(#[allow(deprecated)] Self::Move),
                "BSDIFF" => Some(#[allow(deprecated)] Self::Bsdiff),
                "SOURCE_COPY" => Some(Self::SourceCopy),
                "SOURCE_BSDIFF" => Some(Self::SourceBsdiff),
                "REPLACE_XZ" => Some(Self::ReplaceXz),
                "ZERO" => Some(Self::Zero),
                "DISCARD" => Some(Self::Discard),
                "BROTLI_BSDIFF" => Some(Self::BrotliBsdiff),
                "PUFFDIFF" => Some(Self::Puffdiff),
                "ZUCCHINI" => Some(Self::Zucchini),
                "LZ4DIFF_BSDIFF" => Some(Self::Lz4diffBsdiff),
                "LZ4DIFF_PUFFDIFF" => Some(Self::Lz4diffPuffdiff),
                "REPLACE_ZSTD" => Some(Self::ReplaceZstd),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DstExtent {
    #[prost(uint64, optional, tag = "1")]
    pub num_blocks: ::core::option::Option<u64>,
}
