name: Release Apk

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
          cache: 'gradle'

      - name: Build Apk
        run: ./gradlew assembleRelease

      - name: Sign Android APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNINGKEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_PASS }}
          keyPassword: ${{ secrets.KEY_ALIAS_PASS }}

      - name: Upload Signed APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PayloadDumper-v${{ github.ref_name }}.apk
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}